version: "3"

services: 
  php:
    image: php:fpm-alpine
    container_name: lifeproject-php
    volumes:
      - ./project/api:/var/www/api.localhost

  nginx:
    image: nginx:1.23.2
    container_name: lifeproject-nginx
    build:
        dockerfile: Dockerfile
    volumes:
      - ./project/build:/var/www/life.localhost
      - ./project/api:/var/www/api.localhost
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "80:80"
      - "81:81"

  database:
    image: mariadb:latest
    container_name: lifeproject-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 3313
      MARIADB_DATABASE: "lifeproject"
  
  pma:
    image: phpmyadmin
    container_name: lifeproject-pma
    environment:
      PMA_HOST: database
    ports:
      - "8080:80"
